# Alacritty Configuration - 必要最小限設定

[window]
# ウィンドウのタイトルバーを非表示
decorations = "none"

# ウィンドウの透明度 (0.0で完全透明、1.0で不透明)
opacity = 0.85

[font]
# メインフォント（JetBrains Mono Nerd Font）
normal = { family = "JetBrainsMono Nerd Font" }

[scrolling]
# スクロール時の乗数（高速スクロール）
multiplier = 3

[general]
# ライブ設定リロードを有効化
live_config_reload = true

# ========================================
# Dracula Theme
# ========================================

# Default colors
[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#bd93f9'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#bbbbbb'

# Bright colors
[colors.bright]
black   = '#555555'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#caa9fa'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#ffffff'