# Docker aliases
alias dk='docker'
alias dki='docker images'
alias dkc='docker container'
alias dkl='docker logs'
alias dklf='docker logs -f'
alias dkrm='docker rm'
alias dkrmi='docker rmi'
alias dkps='docker ps'
alias dkpsa='docker ps -a'
alias dkpsq='docker ps -q'
alias dkpsl='docker ps -l'

# Docker Compose aliases
alias dc='docker-compose'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'
alias dcr='docker-compose restart'
alias dce='docker-compose exec'
alias dcl='docker-compose logs'
alias dclf='docker-compose logs -f'
alias dcb='docker-compose build'
alias dcub='docker-compose up --build'
alias dcp='docker-compose ps'